# Generated by Django 6.0.7 on 2026-07-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('explane', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='product/')),
            ],
        ),
    ]
