# Generated by Django 6.0.7 on 2026-07-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brandname', models.CharField(default='', max_length=100)),
                ('contry', models.CharField(default='روژان', max_length=100)),
                ('number', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='product/')),
            ],
        ),
    ]
